<link rel="stylesheet" href="css/reponsive.css">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="footer, address, phone, icons" />
	<title> FOOTER WITH ADDRESS AND PHONES </title>
	<link rel="stylesheet" href="css/demo.css">
	<link rel="stylesheet" href="css/footer-distributed-with-address-and-phones.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
	<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
<footer class="footer-distributed">
	<div class="footer-left">
		<h2><span style="color:#ff7733;"> URBAN XTREME </span></h2>
		
			<p class="footer-company-name" style="color:#ff7733;"> URBAN XTREME &copy; 2019 </p>
			<div class="footer-icons">
						<a href="https://www.facebook.com/urbanxtremeadventures"><i class="fa fa-facebook"></i></a>
						<a href="https://www.youtube.com/channel/UCTeatMZqcozWTwczilShOWw"><i class="fa fa-youtube"></i></a>
						<a href="https://www.instagram.com/urbanxtremeoz/"><i class="fa fa-instagram"></i></a>
			</div>
	</div>

	<div class="footer-center">
		<div>
			<i class="fa fa-map-marker"></i>
			<p class="footer-p" > 6 Wentworth Parade , <br> Balmoral QLD 4171. </p>
		</div>
			<br>
		<div>
			<i class="fa fa-phone"></i>
			<p class="footer-p"> +61-87654321 </p>
		</div>
		<br>
		<div>
		<i class="fa fa-envelope-o"></i>
			<p class="footer-p"><a href="info@urban-xtreme.com.au"> info@urban-xtreme.com.au </a></p>
		</div>
			<br>
	</div>
</footer>
