<link rel="stylesheet" href="css/reponsive.css">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="footer, address, phone, icons" />

	<title>Footer With Address And Phones</title>

	<link rel="stylesheet" href="css/demo.css">
	<link rel="stylesheet" href="css/footer-distributed-with-address-and-phones.css">
	
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

	<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">




<footer class="footer-distributed">

			<div class="footer-left">

				<h3><span> U N I Q U E </span></h3>

				<p class="footer-links">
					<a href="dashboard.php"> Home |</a>
					
					<a href="test.php"> Test | </a>
					
					<a href="courses.php"> Courses </a>
					
					
				</p>

				<p class="footer-company-name"> U N I Q U E &copy; 2019</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span> 6 Wentworth Street</span> Brisbane, Australia</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+61 87654321</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@unique.com">support@unique.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About U N I Q U E</span>
					
					This area still under construction. 
				</p>

				<div class="footer-icons">

					<a href="www.facebook.com"><i class="fa fa-facebook"></i></a>
					<a href="www.twitter.com"><i class="fa fa-twitter"></i></a>
					<a href="www.linkedin.com"><i class="fa fa-linkedin"></i></a>
					<a href="www.github.com"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>

